spring:
  application:
    name: employee-chatbot

  ai:
    openai:
      api-key: ${OPENAI-API-KEY}
    chat:
      client:
        observations:
          include-input: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
