spring:
  application:
    name: employee-chatbot
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
        timeout: 6000s            
      chat:
        options:
          model: llama3.1
      embedding:
        options:
          model: nomic-embed-text