spring:
  application:
    name: employee-chatbot
  ai:
    openai:
      api-key: lm-studio
      base-url: http://localhost:1234
      chat:
        options:
          model: meta-llama-3.1-8b-instruct
